//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS_HR_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int A_ID { get; set; }
        public Nullable<System.DateTime> Enter_Time { get; set; }
        public Nullable<System.DateTime> Exit_Time { get; set; }
        public string Emp_ID { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
