//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS_HR_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCSHRMEntities : DbContext
    {
        public MCSHRMEntities()
            : base("name=MCSHRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Leave_Type> Leave_Type { get; set; }
        public virtual DbSet<Max_Leave_Count> Max_Leave_Count { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Staff_Movements1> Staff_Movements1 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
