//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS_HR_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int P_ID { get; set; }
        public string Position_Title { get; set; }
        public Nullable<System.DateTime> S_Date { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
        public string Status { get; set; }
        public string Emp_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
