//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS_HR_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Movements1
    {
        public int SM_ID { get; set; }
        public string Emp_ID { get; set; }
        public Nullable<System.DateTime> SM_Date { get; set; }
        public Nullable<System.DateTime> S_Time { get; set; }
        public Nullable<System.DateTime> E_Time { get; set; }
        public string Status1 { get; set; }
        public string Place { get; set; }
        public string Reason1 { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
